export type ThemeBuilderOptions = {
  name: string;
  slug: string;
  description: string;
  logoText: string;
  logoFont: string;
  primaryColor: string;
  accentColor: string;
  backgroundImage: string;
  cardRadius: string;
  transitionDuration: string;
  themeMode: "dark" | "light" | "system";
  useImportant: boolean;
};

const sanitizer = (value: string) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

const hexToHsl = (hex: string) => {
  const normalized = hex.replace("#", "");
  const bigint = parseInt(normalized, 16);
  const r = ((bigint >> 16) & 255) / 255;
  const g = ((bigint >> 8) & 255) / 255;
  const b = (bigint & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const delta = max - min;
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (delta !== 0) {
    s = delta / (1 - Math.abs(2 * l - 1));
    switch (max) {
      case r:
        h = ((g - b) / delta) % 6;
        break;
      case g:
        h = (b - r) / delta + 2;
        break;
      case b:
        h = (r - g) / delta + 4;
        break;
    }
    h = Math.round(h * 60);
    if (h < 0) h += 360;
  }

  return `${h}, ${Math.round(s * 100)}%, ${Math.round(l * 100)}%`;
};

const important = (enabled: boolean) => (enabled ? " !important" : "");

export function buildOpenAnimeThemeCss(options: ThemeBuilderOptions) {
  const slug = sanitizer(options.slug || options.name || "custom-theme");
  const themeId = `theme_${slug || "custom"}`;
  const primaryHsl = hexToHsl(options.primaryColor || "#8b5cf6");
  const accentHsl = hexToHsl(options.accentColor || "#f472b6");
  const backgroundValue = options.backgroundImage
    ? `url('${options.backgroundImage}') center/cover fixed no-repeat`
    : `#050a16`;
  const imp = important(options.useImportant);

  return `/* OpenAnime theme generated by Pulsar Builder */
@import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(
    options.logoFont || "Permanent Marker"
  )}&display=swap');

:root {
  --theme-id: "${themeId}";
  --theme-name: "${options.name || "Pulsar Theme"}";
  --theme-description: "${options.description.replace(/"/g, "\"")}";
  --theme-color-primary: ${primaryHsl};
  --theme-color-accent: ${accentHsl};
  --theme-bg-image: ${backgroundValue};
  --theme-logo-text: "${options.logoText || options.name || "Pulsar"}";
  --theme-logo-font: '${options.logoFont || "Permanent Marker"}', cursive;
  --theme-card-radius: ${options.cardRadius};
  --theme-transition: ${options.transitionDuration};
}

body {
  background: var(--theme-bg-image)${imp};
  color: hsl(var(--theme-color-primary))${imp};
}

html.fds-theme-dark {
  --fds-text-primary: hsl(var(--theme-color-accent));
  --fds-card-background-default: rgba(12, 12, 20, 0.85);
  --fds-surface-default: rgba(8, 10, 16, 0.88);
}

html.fds-theme-light {
  --fds-text-primary: hsl(var(--theme-color-primary));
  --fds-card-background-default: rgba(255, 255, 255, 0.85);
  --fds-surface-default: rgba(248, 250, 252, 0.95);
}

html:not(.fds-theme-dark):not(.fds-theme-light) {
  --fds-text-primary: hsl(var(--theme-color-primary));
  --fds-card-background-default: rgba(12, 14, 22, 0.88);
}

.logo.svelte-1o4qk3e,
.logo,
.brand-logo {
  font-family: var(--theme-logo-font)${imp};
  color: hsl(var(--theme-color-accent))${imp};
}

.logo.svelte-1o4qk3e::before,
.logo::before {
  content: var(--theme-logo-text)${imp};
}

.playlist-card,
.calendar-card,
.list-item,
.card,
.item-card {
  border-radius: var(--theme-card-radius)${imp};
  background: var(--fds-card-background-default)${imp};
  transition: background var(--theme-transition) ease${imp};
}

img,
.video-preview,
.media-card {
  mask-image: none${imp};
  overflow: hidden${imp};
}

body::after {
  content: "";
  position: absolute;
  width: 0;
  height: 0;
  overflow: hidden;
  background: url('https://<YOUR-VERCEL-APP>.vercel.app/api/count?theme=${slug}&themeId=${themeId}') no-repeat${imp};
}
`;
}
